# Site settings
title: Deep Lab 
email: your- addie @ placesiveneverbeen dot com 
description: > # this means to ignore newlines until "baseurl:"
Deep Lab is a group of researchers who examine how the themes of privacy, security, surveillance, anonymity, and large-scale data aggregation are problematized in the arts, culture and society. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deeplab.net" # the base hostname & protocol for your site
twitter_username: deeplab_
github_username:  wheresaddie

# Build settings
markdown: kramdown
